#!/usr/bin/env python3
"""
Post or update a sticky PR comment summarizing a local CARL loop run.

Requires:
  - gh CLI installed and authenticated
  - current branch associated with an open PR

Usage example:
  python post_carl_summary_comment.py \
    --status COMPLETE \
    --base main \
    --iterations 3 \
    --fixed 7 \
    --deferred 1 \
    --remaining 0 \
    --checks passed \
    --review-ids "019c...,019d..."
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any

COMMAND_TIMEOUT_SECONDS = 120
MARKER = "<!-- carl-local-loop -->"


class ScriptError(RuntimeError):
    """Script-level failure with actionable message."""


def _is_no_open_pr_error(error: ScriptError) -> bool:
    msg = str(error).lower()
    return "no pull requests found" in msg


def _run(cmd: list[str], stdin: str | None = None) -> str:
    try:
        proc = subprocess.run(
            cmd,
            input=stdin,
            capture_output=True,
            text=True,
            timeout=COMMAND_TIMEOUT_SECONDS,
        )
    except FileNotFoundError as exc:
        raise ScriptError(f"Command not found: {cmd[0]}") from exc
    except subprocess.TimeoutExpired as exc:
        raise ScriptError(
            f"Command timed out after {COMMAND_TIMEOUT_SECONDS}s: {' '.join(cmd)}"
        ) from exc

    if proc.returncode != 0:
        raise ScriptError(f"Command failed: {' '.join(cmd)}\n{proc.stderr.strip()}")
    return proc.stdout


def _run_json(cmd: list[str], stdin: str | None = None) -> dict[str, Any]:
    out = _run(cmd, stdin=stdin)
    try:
        return json.loads(out)
    except json.JSONDecodeError as exc:
        raise ScriptError(f"Invalid JSON output from command: {' '.join(cmd)}") from exc


def _ensure_gh_authenticated() -> None:
    _run(["gh", "auth", "status"])


@dataclass
class PullRequestContext:
    number: int
    url: str
    title: str
    repo: str


def _current_pr_context() -> PullRequestContext:
    pr = _run_json(["gh", "pr", "view", "--json", "number,url,title"])
    number = int(pr["number"])
    url = str(pr["url"])
    title = str(pr.get("title", ""))
    repo = _run(["gh", "repo", "view", "--json", "nameWithOwner", "--jq", ".nameWithOwner"]).strip()
    return PullRequestContext(number=number, url=url, title=title, repo=repo)


def _list_bot_comments(pr_number: int, repo: str) -> list[dict[str, Any]]:
    payload = _run_json(
        [
            "gh",
            "api",
            f"/repos/{repo}/issues/{pr_number}/comments",
            "--paginate",
        ]
    )
    if isinstance(payload, list):
        return payload
    raise ScriptError("Unexpected response while listing PR comments")


def _find_existing_comment_id(pr_number: int, repo: str) -> int | None:
    comments = _list_bot_comments(pr_number, repo)
    for c in comments:
        body = str(c.get("body", ""))
        if MARKER in body:
            comment_id = c.get("id")
            if isinstance(comment_id, int):
                return comment_id
    return None


def _iso_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def build_comment_body(
    *,
    status: str,
    base: str,
    iterations: int,
    fixed: int,
    deferred: int,
    remaining: int,
    checks: str,
    review_ids: list[str],
    notes: str | None,
) -> str:
    rid_line = ", ".join(review_ids) if review_ids else "none"
    note_line = notes.strip() if notes else "none"
    return "\n".join(
        [
            MARKER,
            "### CARL Local Loop Summary",
            "",
            f"- status: `{status}`",
            f"- base: `{base}`",
            f"- iterations: `{iterations}`",
            f"- fixed: `{fixed}`",
            f"- deferred: `{deferred}`",
            f"- remaining: `{remaining}`",
            f"- checks: `{checks}`",
            f"- review_ids: `{rid_line}`",
            f"- notes: {note_line}",
            f"- updated_at_utc: `{_iso_now()}`",
            "",
            "_Generated by local CARL run._",
        ]
    )


def _update_comment(comment_id: int, repo: str, body: str) -> None:
    _run(
        [
            "gh",
            "api",
            "--method",
            "PATCH",
            f"/repos/{repo}/issues/comments/{comment_id}",
            "-f",
            f"body={body}",
        ]
    )


def _create_comment(pr_number: int, repo: str, body: str) -> None:
    _run(
        [
            "gh",
            "api",
            "--method",
            "POST",
            f"/repos/{repo}/issues/{pr_number}/comments",
            "-f",
            f"body={body}",
        ]
    )


def _parse_review_ids(raw: str) -> list[str]:
    values = [x.strip() for x in raw.split(",")]
    return [x for x in values if x]


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--status", required=True, choices=["COMPLETE", "BLOCKED", "MAX_ITERATIONS_REACHED"])
    parser.add_argument("--base", default="main")
    parser.add_argument("--iterations", type=int, required=True)
    parser.add_argument("--fixed", type=int, required=True)
    parser.add_argument("--deferred", type=int, required=True)
    parser.add_argument("--remaining", type=int, required=True)
    parser.add_argument("--checks", required=True, help="passed|failed|not_run")
    parser.add_argument("--review-ids", default="", help="Comma-separated review IDs")
    parser.add_argument("--notes", default="", help="Optional free-form summary note")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print comment body and whether create/update would happen without mutating GitHub.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])

    try:
        _ensure_gh_authenticated()
        try:
            pr = _current_pr_context()
        except ScriptError as exc:
            if _is_no_open_pr_error(exc):
                print("No open PR found for current branch; skipping CARL summary comment publish.")
                return 0
            raise
        review_ids = _parse_review_ids(args.review_ids)
        body = build_comment_body(
            status=args.status,
            base=args.base,
            iterations=args.iterations,
            fixed=args.fixed,
            deferred=args.deferred,
            remaining=args.remaining,
            checks=args.checks,
            review_ids=review_ids,
            notes=args.notes,
        )

        existing_comment_id = _find_existing_comment_id(pr.number, pr.repo)
        action = "update" if existing_comment_id is not None else "create"

        if args.dry_run:
            print(f"DRY_RUN action={action} repo={pr.repo} pr={pr.number}")
            print(body)
            return 0

        if existing_comment_id is not None:
            _update_comment(existing_comment_id, pr.repo, body)
            print(f"Updated CARL summary comment (id={existing_comment_id}) on {pr.repo}#{pr.number}")
        else:
            _create_comment(pr.number, pr.repo, body)
            print(f"Created CARL summary comment on {pr.repo}#{pr.number}")
        return 0
    except ScriptError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
